/*

MART Tables (Business Layer)
Now we build final business tables using STAGE data.
    joins happen
    business logic happens
    reporting happens

*/

USE DATABASE LICENSING_DB;
USE SCHEMA MART;

--Create DIM_LICENSE
CREATE OR REPLACE TABLE DIM_LICENSE AS
SELECT
    LICENSE_ID,
    PERSON_ID,
    LICENSE_TYPE,
    ISSUE_DATE,
    EXPIRY_DATE,
    STATUS AS LICENSE_STATUS
FROM LICENSING_DB.STAGE.STG_LICENSES;

--Create FACT_VIOLATION
CREATE OR REPLACE TABLE FACT_VIOLATION AS
SELECT
    V.VIOLATION_ID,
    V.LICENSE_ID,
    V.VIOLATION_TYPE,
    V.VIOLATION_DATE,
    V.AMOUNT,
    V.STATUS AS VIOLATION_STATUS
FROM LICENSING_DB.STAGE.STG_VIOLATIONS V;

--Create FACT_PAYMENT
CREATE OR REPLACE TABLE FACT_PAYMENT AS
SELECT
    P.PAYMENT_ID,
    P.LICENSE_ID,
    P.PAYMENT_DATE,
    P.PAYMENT_AMOUNT,
    P.PAYMENT_METHOD,
    P.PAYMENT_STATUS
FROM LICENSING_DB.STAGE.STG_PAYMENTS P;

--Create FACT_TRANSACTION
CREATE OR REPLACE TABLE FACT_TRANSACTION AS
SELECT
    T.TRANSACTION_ID,
    T.PAYMENT_ID,
    T.TRANSACTION_DATE,
    T.TRANSACTION_AMOUNT,
    T.CARD_TYPE,
    T.TRANSACTION_STATUS
FROM LICENSING_DB.STAGE.STG_TRANSACTIONS T;