--Licenses with OPEN Violations
SELECT
    L.LICENSE_ID,
    L.PERSON_ID,
    L.LICENSE_STATUS,
    V.VIOLATION_ID,
    V.VIOLATION_TYPE,
    V.VIOLATION_STATUS
FROM LICENSING_DB.MART.DIM_LICENSE L
JOIN LICENSING_DB.MART.FACT_VIOLATION V
    ON L.LICENSE_ID = V.LICENSE_ID
WHERE V.VIOLATION_STATUS = 'OPEN';

--Total Payment Summary
SELECT
    PAYMENT_STATUS,
    COUNT(*) AS PAYMENT_COUNT,
    SUM(PAYMENT_AMOUNT) AS TOTAL_AMOUNT
FROM LICENSING_DB.MART.FACT_PAYMENT
GROUP BY PAYMENT_STATUS;


select *  FROM LICENSING_DB.MART.FACT_VIOLATION V;
select * from LICENSING_DB.MART.FACT_PAYMENT P;

SELECT
    V.LICENSE_ID,
    COUNT(V.VIOLATION_ID) AS VIOLATION_COUNT
FROM LICENSING_DB.MART.FACT_VIOLATION V
LEFT JOIN LICENSING_DB.MART.FACT_PAYMENT P
    ON V.LICENSE_ID = P.LICENSE_ID
WHERE P.LICENSE_ID IS NULL
GROUP BY V.LICENSE_ID;


--Transaction Status Summary
SELECT
    TRANSACTION_STATUS,
    COUNT(*) AS CNT,
    SUM(TRANSACTION_AMOUNT) AS TOTAL_AMOUNT
FROM LICENSING_DB.MART.FACT_TRANSACTION
GROUP BY TRANSACTION_STATUS;