CREATE OR REPLACE STAGE adls_raw_stage
STORAGE_INTEGRATION = azure_adls_int
URL = 'azure://licdatadldev01.blob.core.windows.net/rawdata/raw/'
FILE_FORMAT = LICENSING_DB.RAW.CSV_FMT;

LIST @adls_raw_stage/licenses;
LIST @adls_raw_stage/violations;
LIST @adls_raw_stage/payments;
LIST @adls_raw_stage/transactions;

--Load LICENSES
COPY INTO LICENSING_DB.RAW.RAW_LICENSES
FROM @adls_raw_stage/licenses/
FILE_FORMAT = (FORMAT_NAME = LICENSING_DB.RAW.CSV_FMT);

--Load VIOLATIONS
COPY INTO LICENSING_DB.RAW.RAW_VIOLATIONS
FROM @adls_raw_stage/violations/
FILE_FORMAT = (FORMAT_NAME = LICENSING_DB.RAW.CSV_FMT);

--Load Payment 
COPY INTO LICENSING_DB.RAW.RAW_PAYMENTS
FROM @adls_raw_stage/payments/
FILE_FORMAT = (FORMAT_NAME = LICENSING_DB.RAW.CSV_FMT);

--Load TRANSACTIONS
COPY INTO LICENSING_DB.RAW.RAW_TRANSACTIONS
FROM @adls_raw_stage/transactions/
FILE_FORMAT = (FORMAT_NAME = LICENSING_DB.RAW.CSV_FMT);

--Validate_Data 
SELECT 'RAW_LICENSES' AS TABLE_NAME, COUNT(*) FROM LICENSING_DB.RAW.RAW_LICENSES
UNION ALL
SELECT 'RAW_VIOLATIONS', COUNT(*) FROM LICENSING_DB.RAW.RAW_VIOLATIONS
UNION ALL
SELECT 'RAW_PAYMENTS', COUNT(*) FROM LICENSING_DB.RAW.RAW_PAYMENTS
UNION ALL
SELECT 'RAW_TRANSACTIONS', COUNT(*) FROM LICENSING_DB.RAW.RAW_TRANSACTIONS;