/*
--Creating Database 
CREATE DATABASE LICENSING_DB;

USE DATABASE LICENSING_DB;

--Schema Creation
CREATE SCHEMA RAW;
CREATE SCHEMA STAGE;
CREATE SCHEMA MART;

To Display Schemas 
SHOW SCHEMAS;


USE DATABASE LICENSING_DB;
USE SCHEMA RAW;

CREATE OR REPLACE TABLE RAW_LICENSES (
    LICENSE_ID STRING,
    PERSON_ID STRING,
    LICENSE_TYPE STRING,
    ISSUE_DATE STRING,
    EXPIRY_DATE STRING,
    STATUS STRING
);

CREATE OR REPLACE TABLE RAW_VIOLATIONS (
    VIOLATION_ID STRING,
    LICENSE_ID STRING,
    VIOLATION_TYPE STRING,
    VIOLATION_DATE STRING,
    AMOUNT STRING,
    STATUS STRING
);

CREATE OR REPLACE TABLE RAW_PAYMENTS (
    PAYMENT_ID STRING,
    LICENSE_ID STRING,
    PAYMENT_DATE STRING,
    PAYMENT_AMOUNT STRING,
    PAYMENT_METHOD STRING,
    PAYMENT_STATUS STRING
);

CREATE OR REPLACE TABLE RAW_TRANSACTIONS (
    TRANSACTION_ID STRING,
    PAYMENT_ID STRING,
    TRANSACTION_DATE STRING,
    TRANSACTION_AMOUNT STRING,
    CARD_TYPE STRING,
    TRANSACTION_STATUS STRING
);


*/

SHOW TABLES IN SCHEMA LICENSING_DB.RAW;



