/*
Load CSV Files
USE DATABASE LICENSING_DB;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT CSV_FMT
TYPE = 'CSV'
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

This tells Snowflake:
    file type is CSV
    first row is header
    values may be inside quotes

*/
select * FROM LICENSING_DB.RAW.RAW_LICENSES

SELECT 'RAW_LICENSES' AS TABLE_NAME, COUNT(*) AS CNT FROM LICENSING_DB.RAW.RAW_LICENSES
UNION ALL
SELECT 'RAW_VIOLATIONS', COUNT(*) FROM LICENSING_DB.RAW.RAW_VIOLATIONS
UNION ALL
SELECT 'RAW_PAYMENTS', COUNT(*) FROM LICENSING_DB.RAW.RAW_PAYMENTS
UNION ALL
SELECT 'RAW_TRANSACTIONS', COUNT(*) FROM LICENSING_DB.RAW.RAW_TRANSACTIONS;