/*
Transform RAW to STAGE

Now we will create cleaned tables in the STAGE schema.

Purpose:

convert strings to proper data types
keep only clean usable data
prepare for joins and business reporting


*/
USE DATABASE LICENSING_DB;
USE SCHEMA STAGE;

CREATE OR REPLACE TABLE STG_LICENSES AS
SELECT
    LICENSE_ID,
    PERSON_ID,
    LICENSE_TYPE,
    TRY_TO_DATE(ISSUE_DATE, 'YYYY-MM-DD') AS ISSUE_DATE,
    TRY_TO_DATE(EXPIRY_DATE, 'YYYY-MM-DD') AS EXPIRY_DATE,
    STATUS
FROM LICENSING_DB.RAW.RAW_LICENSES
WHERE LICENSE_ID IS NOT NULL;

CREATE OR REPLACE TABLE STG_VIOLATIONS AS
SELECT
    VIOLATION_ID,
    LICENSE_ID,
    VIOLATION_TYPE,
    TRY_TO_DATE(VIOLATION_DATE, 'YYYY-MM-DD') AS VIOLATION_DATE,
    TRY_TO_DECIMAL(AMOUNT, 10, 2) AS AMOUNT,
    STATUS
FROM LICENSING_DB.RAW.RAW_VIOLATIONS
WHERE VIOLATION_ID IS NOT NULL;

CREATE OR REPLACE TABLE STG_PAYMENTS AS
SELECT
    PAYMENT_ID,
    LICENSE_ID,
    TRY_TO_DATE(PAYMENT_DATE, 'YYYY-MM-DD') AS PAYMENT_DATE,
    TRY_TO_DECIMAL(PAYMENT_AMOUNT, 10, 2) AS PAYMENT_AMOUNT,
    PAYMENT_METHOD,
    PAYMENT_STATUS
FROM LICENSING_DB.RAW.RAW_PAYMENTS
WHERE PAYMENT_ID IS NOT NULL;

CREATE OR REPLACE TABLE STG_TRANSACTIONS AS
SELECT
    TRANSACTION_ID,
    PAYMENT_ID,
    TRY_TO_DATE(TRANSACTION_DATE, 'YYYY-MM-DD') AS TRANSACTION_DATE,
    TRY_TO_DECIMAL(TRANSACTION_AMOUNT, 10, 2) AS TRANSACTION_AMOUNT,
    CARD_TYPE,
    TRANSACTION_STATUS
FROM LICENSING_DB.RAW.RAW_TRANSACTIONS
WHERE TRANSACTION_ID IS NOT NULL;


SHOW TABLES IN SCHEMA LICENSING_DB.STAGE;


--Verfying Staging Data Count 

SELECT 'STG_LICENSES' AS TABLE_NAME, COUNT(*) AS CNT FROM LICENSING_DB.STAGE.STG_LICENSES
UNION ALL
SELECT 'STG_VIOLATIONS', COUNT(*) FROM LICENSING_DB.STAGE.STG_VIOLATIONS
UNION ALL
SELECT 'STG_PAYMENTS', COUNT(*) FROM LICENSING_DB.STAGE.STG_PAYMENTS
UNION ALL
SELECT 'STG_TRANSACTIONS', COUNT(*) FROM LICENSING_DB.STAGE.STG_TRANSACTIONS;